layout_spectrum: 0.698711
color:
  saturation: 0.7305481
  lightness: 0.2784942
  brandStrength: 0.4981761
  brandColors:
    - '#F1FCFB'
    - '#9AA3A5'
    - '#0E272F'
    - '#88BDE9'
    - '#4280BD'
  rhythmicContrast: 0.9220266
typography_spectrum: 0.3861439
name: Holistic Living Centers
